version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  web-0:
    image: boxboat/hello-world-webapp
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    environment:
      - PORT=8080
  web-1:
    image: boxboat/hello-world-webapp
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    environment:
      - PORT=8080
volumes:
  db:
    driver: local